version: '3.8'
services:
  codered-web:
    build: .
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: codered-redis
      REDIS_PORT: 6379
      POSTGRES_HOST: codered-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    depends_on:
      - codered-redis
      - codered-postgres

  codered-redis:
    image: redis:latest
    ports:
      - '6379:6379'

  codered-postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
