version: '3.8'
services:
  codered-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run test:ci
    depends_on:
      - codered-postgresql
      - codered-redis
    networks:
      - compose-networks

  codered-postgresql:
    image: postgis/postgis
    restart: always
    container_name: codered-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    networks:
      - compose-networks

  codered-redis:
    image: redis:latest
    container_name: codered-redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    restart: always
    networks:
      - compose-networks

networks:
  compose-networks:
    driver: bridge
