name: Deploy and Test Redis to Amazon ECS

on:
  push:
    branches: [deploy-to-ecs-fargate]

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: codered-redis
  ECS_SERVICE: codered-redis-service
  ECS_CLUSTER: DevCluster
  ECS_TASK_DEFINITION: ./codered-redis-task-definition.json
  CONTAINER_NAME: codered-redis

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      redis:
        image: redis:7.0.15-alpine
        #health check 추가
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: CheckOut repository code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript project
        run: npm run build

        #Redis 연결 시도 추가
      - name: Connect to Redis
        run: node dist/notifications/redis/redis.client.js
        env:
          REDIS_HOST: codered-reids
          REDIS_PORT: 6379

  deploy:
    needs: test
    runs-on: [ubuntu-latest]
    environment: production

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}

        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
